### ISSUE TITLE
Interface to change base pitch

### ISSUE THREAD

**Issue by richard92m** [richard92m/sigs#15]
Select from A-G; provide counter for moving octaves.

**Comment by nick5435** [comment]
I will implement this now. It will be be a json object, call it with `notes[int octave_number][str Note Name]`, where note name is C0->B8. A4 is 440hz. Is in file js/notes.js

**Comment by nick5435** [comment]
Closed.

**Comment by richard92m** [comment]
Great. We could probably calculate a lot of that, but given that it's finite (and fairly short) I don't think that's necessary and it provides a clean way to access these numbers.

UI elements to change the base note/octave still needed.
