### ISSUE TITLE
Make wireless

### ISSUE THREAD

**Issue by richard92m** [richard92m/sigs#6]
I have a [JY-MCU](https://core-electronics.com.au/attachments/guides/Product-User-Guide-JY-MCU-Bluetooth-UART-R1-0.pdf) bluetooth module that's fairly trivial to configure.

**Comment by nick5435** [comment]
I have an Arduino Mega that we can use for this. We'll need the extra oomph. I will add this to my project board and bring the Mega down with me after break.

**Comment by richard92m** [comment]
Great. We'll definitely need it down the road.

**Comment by richard92m** [comment]
JY-MCU module up and working. Wired data connection no longer needed. Power currently provided by a rechargeable [lithium backpack](http://www.liquidware.com/shop/show/mbp/lithium+backpack).

**Comment by nick5435** [comment]
I have packed this. I am also bringing down an arduino Due, which should be even more capable to handle the throughput. I also have a bunch of other sensors and hardware that we could use.
