### ISSUE TITLE
Translated sawtooth

### ISSUE THREAD

**Issue by richard92m** [richard92m/sigs#8]
All other waves work as expected, like so:

![sigs_screenshot](https://cloud.githubusercontent.com/assets/8980489/20901730/7e49db60-baf9-11e6-8b95-ad5ed74fa1f4.png)
 

Sawtooth, however looks like this (no modulation):
![screen shot 2016-12-05 at 2 40 54 pm](https://cloud.githubusercontent.com/assets/8980489/20901709/63de9004-baf9-11e6-99e8-15197e4babae.png)

And with amplitude modulation:
![screen shot 2016-12-05 at 2 41 00 pm](https://cloud.githubusercontent.com/assets/8980489/20901736/86e83348-baf9-11e6-9e3d-7ad276643724.png)

Is this correct behavior?

**Comment by nick5435** [comment]
I will look into it.

**Comment by nick5435** [comment]
The mathematics behind the wave is working. I have tested the algorithm in a python environment, perhaps the way that the modulation is being done is weird?

**Comment by richard92m** [comment]
It was an issue with the cleanWave() I created; sometimes I only want a single oscillation.

 Grabbing a single wave from the entire set was a little different for saw than the others.
